# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'
        span:
            line_numbers: false
        block:
            line_numbers: true
            start_line: 1
# Setup
title:           Jun's 
tagline:          '이것 저것'
description:     이것 저것 쓰는 블로그 
url:              https://chatsh1re.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
remote_theme: fongandrew/hydeout

author:
  name:           'Jun'
  url:            #https://twitter.com/fongandrewc

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-last-modified-at
  - jekyll-sitemap

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
disqus:
    shortname: chatsh1re
